backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "portfolio"
    label: "Portfolio Designs"
    files:
      - name: "designs"
        label: "Designs"
        file: "portfolio-data.json"
        fields:
          - label: "Design"
            name: "designs"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Image description (for accessibility)", name: "alt", widget: "string"}
              - {label: "Design name", name: "name", widget: "string"}
              - {label: "Description", name: "desc", widget: "text"}
              - label: "Details"
                name: "details"
                widget: "list"
                summary: "{{fields.label}}: {{fields.val}}"
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - {label: "Value", name: "val", widget: "string"}
